firewall fix

diff --git a/ipsec-partner b/ipsec-partner
--- a/ipsec-partner
+++ b/ipsec-partner
@@ -698,24 +698,6 @@ EOF
     fi
 
     #
-    # configure firewalld
-    #
-    err=0
-    systemctl start firewalld
-    firewall-cmd --zone=internal --add-interface=$if_local --permanent || ((err = err + 1))
-    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i ens3 -p tcp --dport 22 -j ACCEPT || ((err = err + 1))
-    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -o ens3 -p tcp --sport 22 -j ACCEPT || ((err = err + 1))
-    firewall-cmd --reload || ((err = err + 1))
-    firewall-cmd --get-active-zones || ((err = err + 1))
-    if [ $err -gt 0 ]; then
-        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-        echo "Warning: Firewall configured with errors."
-        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
-    else
-        echo "Firewall configured."
-    fi
-
-    #
     # Configure services
     #
     systemctl start ipsec
@@ -726,6 +708,21 @@ EOF
     systemctl enable firewalld
     echo "Services configured to start at boot."
 
+    #
+    # configure firewalld
+    #
+    err=0
+    firewall-cmd --zone=internal --add-interface=$if_local --permanent || ((err = err + 1))
+    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -i ens3 -p tcp --dport 22 -j ACCEPT || ((err = err + 1))
+    firewall-cmd --direct --permanent --add-rule ipv4 filter FORWARD 0 -o ens3 -p tcp --sport 22 -j ACCEPT || ((err = err + 1))
+    firewall-cmd --reload || ((err = err + 1))
+    if [ $err -gt 0 ]; then
+        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+        echo "Warning: Firewall configured with errors."
+        echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
+    else
+        echo "Firewall configured."
+    fi
 
     echo "Status of firewall service."
     firewall-cmd --state
@@ -733,6 +730,7 @@ EOF
 
     echo "Status of ipsec service."
     ipsec verify
+
 
     #
     # Install ipsec-partner
